--ddl data definition language modelar e criar

--dml data manipulation language manipular

--ddl
-- CREATE DATABASE TUMARC;

-- CREATE TABLE ALUNOS
-- (
--     MATRICULA INT CONSTRAINT PK_ALUNOS PRIMARY KEY,
--     NOME CHAR(50)
-- );

-- INSERT ALUNOS (MATRICULA, NOME) VALUES (2,'IGOR')

-- SELECT * FROM ALUNOS

-- ALTER TABLE ALUNOS ADD DATANASCIMENTO DATE

-- USE TUMARC;
 
-- UPDATE ALUNOS SET DATANASCIMENTO = '03/21/2006' WHERE MATRICULA = 1

-- SELECT * FROM ALUNOS

-- CREATE TABLE BOLSAS
-- (
--     IDBOLSA INT CONSTRAINT PK_BOLSA PRIMARY KEY,
--     MATRICULA INT,
--     VALOR MONEY
-- )

-- ALTER TABLE BOLSAS ADD CONSTRAINT FK_BOLSAS_ALUNOS FOREIGN KEY(MATRICULA)
-- REFERENCES ALUNOS(MATRICULA)

-- SELECT * FROM BOLSAS

-- INSERT BOLSAS (IDBOLSA, MATRICULA, VALOR)
-- VALUES (170,1,100.00)
